/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    posts: Post;
    postCategories: PostCategory;
    users: User;
  };
  globals: {
    menu: Menu;
  };
}
export interface Post {
  id: string;
  text?: string;
  category?: string | PostCategory;
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface PostCategory {
  id: string;
  name?: string;
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Menu {
  id: string;
  globalText?: string;
}
